### ISSUE TITLE
Error when calling RPi.GPIO.cleanup without arguments

### ISSUE THREAD

**Issue by nils-van-zuijlen** [MomsFriendlyRobotCompany/fake_rpi#7]
I got an `IndexError` when calling `RPi.GPIO.cleanup` without arguments.

```
int.setmode()
int.setup(1,)
int.setup(0,)
int.output(True,)
int.output(False,)
int.input(): 1
1
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    GPIO.cleanup()
  File "/usr/local/lib/python3.5/dist-packages/fake_rpi/wrappers.py", line 19, in wrapped
    c = str(args[0].__class__).split('\'')
IndexError: tuple index out of range
```

``` python
# Replace libraries by fake ones
import sys
import fake_rpi

sys.modules['RPi'] = fake_rpi.RPi     # Fake RPi (GPIO)
#sys.modules['smbus'] = fake_rpi.smbus # Fake smbus (I2C)

from RPi import GPIO
import random, time


GPIO.setmode(GPIO.BOARD)

GPIO.setup(1, GPIO.IN)
GPIO.setup(2, GPIO.OUT)

GPIO.output(2, True)
GPIO.output(2, False)

input1 = GPIO.input(1)

print(input1)

GPIO.cleanup()
```

**Comment by walchko** [comment]
I will take a look

**Comment by nils-van-zuijlen** [comment]
Oops, I didn't mention I ran this with python3.6 :-1:

**Comment by walchko** [comment]
Sorry, I am really busy right now. It is due to the fact I am using wrappers and you have found an issue I didn't expect. This originally came from  a pull request from someone else and it seemed to work correctly at the time. I will get to it, but it might be a little ... sorry.

**Comment by walchko** [comment]
I pushed an update that I think fixes the issue

**Comment by walchko** [comment]
oh, I had to make some small changes to get things to work right. I added this code to my unit tests and it works on my macbook.

```python
# Faking
import sys
import fake_rpi

sys.modules['RPi'] = fake_rpi.RPi
sys.modules['RPi.GPIO'] = fake_rpi.RPi.GPIO

def test_gpio():
	GPIO.setmode(GPIO.BOARD)
	GPIO.setup(1, GPIO.IN)
	GPIO.setup(2, GPIO.OUT)
	GPIO.output(2, True)
	GPIO.output(2, False)
	GPIO.getmode()
	input1 = GPIO.input(1)
	GPIO.cleanup()
        assert True
```
